//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoristeee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int Id { get; set; }
        public int SedisteId { get; set; }
        public Nullable<int> KorisnikId { get; set; }
        public int ProjekcijaId { get; set; }
    
        public virtual Projekcija Projekcija { get; set; }
        public virtual Sediste Sediste { get; set; }
    }
}
