//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoristeee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Sifra { get; set; }
        public string Rola { get; set; }
    
        public virtual Pozoriste Pozoriste { get; set; }
    }
}
