//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoristeee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container3 : DbContext
    {
        public Model1Container3()
            : base("name=Model1Container3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pozoriste> Pozoristes { get; set; }
        public virtual DbSet<Repertoar> Repertoars { get; set; }
        public virtual DbSet<Predstava> Predstavas { get; set; }
        public virtual DbSet<Projekcija> Projekcijas { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Sediste> Sedistes { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Najava> Najavas { get; set; }
        public virtual DbSet<Karta> Kartas { get; set; }
        public virtual DbSet<Glumac> Glumacs { get; set; }
    }
}
