//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoristeee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozoriste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pozoriste()
        {
            this.Salas = new HashSet<Sala>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Ulica { get; set; }
        public string Grad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sala> Salas { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Repertoar Repertoar { get; set; }
    }
}
